id: P010575
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-20 10:14:48.868173
source_metadata:
  id: bdr:W1KG21707
  title: ཕྱུགས་གསོ་བདུད་རྩིའི་རྫིང་བུ།
  author: ''
  volumes:
    4a0be7284458459d80652014a241771a:
      image_group_id: I1KG21768
      title: ''
      volume_number: 1
      total_pages: 750
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
