id: P010575
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21707
  title: ཕྱུགས་གསོ་བདུད་རྩིའི་རྫིང་བུ།
  author: ''
  volumes:
    4a0be7284458459d80652014a241771a:
      image_group_id: I1KG21768
      title: ''
      volume_number: 1
      total_pages: 750
