id: IC647A90B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T22:24:42+00:00'
last_modified: '2022-06-08T14:36:33.827658+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21707
  title: ཕྱུགས་གསོ་བདུད་རྩིའི་རྫིང་བུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E5B5:
      image_group_id: I1KG21768
      title: ''
      total_pages: 750
      order: 1
      base_file: E5B5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
